version: 2.1 # use CircleCI 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/cloudfoundry-community/splunk-firehose-nozzle
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run:
          name: Install Dependencies
          command: |
            curl https://glide.sh/get | sh
            go get -t ./...
      - run:
          name: Builder
          command: make build
      - run:
          name: Run unit tests
          command: |
            make testall
            cp splunk-firehose-nozzle /tmp
      - persist_to_workspace:
          root: /tmp
          paths:
            - splunk-firehose-nozzle

  deploy-nozzle:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/cloudfoundry-community/splunk-firehose-nozzle
    steps: # steps that comprise the `deploy` job
      - attach_workspace:
          at: /tmp
      - checkout # check out source code to working directory
      - run:
          name: Install dependencies
          command: |
            curl https://glide.sh/get | sh
            go get -t ./...
            cp -R /tmp/splunk-firehose-nozzle .
      - run:
          name: Deploy nozzle
          command: |
            .circleci/update_manifest.sh
            .circleci/pre-req.sh
            cf push -f .circleci/ci_nozzle_manifest.yml -u process --random-route

  tile-builder:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/cloudfoundry-community/splunk-firehose-nozzle
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: Tile builder
          command: |
            cp -R /tmp/splunk-firehose-nozzle .
            .circleci/tile-builder.sh
      - run:
          name: Push tile to internal s3
          command: |
            cp -R /tmp/splunk-firehose-nozzle .
            .circleci/push_tile.sh
      - teardown

  execute_tests:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/python:3.7
    working_directory: /go/src/github.com/cloudfoundry-community/splunk-firehose-nozzle
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: Install dependencies
          command: |
            curl https://glide.sh/get | sh
            go get -t ./...
            cp -R /tmp/splunk-firehose-nozzle .
      - run:
          name: Deploy data-gen
          command: |
            .circleci/pre-req.sh
            cf push -f .circleci/data_gen_manifest.yml -u process -p tools/data_gen --random-route
            sleep 10
      - run:
          name: Prepare test environment
          command: |
            .circleci/pre-functional-test.sh
      - run:
          name: Executing tests
          command: |
            .circleci/functional-test.sh
      - when:
          condition: ${CIRCLE_BRANCH} != dev/fix-master-ci-failure
          steps:
            - teardown

commands:
  teardown:
    description: Teardown deployment env
    steps:
      - run:
          name: Teardown
          command: |
            cf delete splunk-firehose-nozzle -f
            cf delete data_gen -f
            cf delete-org splunk-ci-org -f
          when:
            always

workflows:
  version: 2.1
  build-and-deploy-nozzle:
    jobs:
      - build
      - deploy-nozzle:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
                - dev/fix-master-ci-failure
      - tile-builder:
          requires:
            - execute_tests
          filters:
            branches:
              only:
                - master
                - dev/fix-master-ci-failure
      - execute_tests:
          requires:
            - deploy-nozzle
          filters:
            branches:
              only:
                - develop
                - master
                - dev/fix-master-ci-failure
